name: Quick Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        cd customer-service && npm install
        cd ../product-service && npm install
        cd ../order-service && npm install
        cd ../payment-service && npm install
        cd ../transaction-worker && npm install
        cd ../integration-tests && npm install

    - name: Run unit tests only
      run: |
        cd payment-service && npm test
        cd ../transaction-worker && npm test
